package com.etherblood.aoe2.ai.core.variables.system;

public enum SystemSymbols implements SystemSymbol {
    //Game Type
    DEATH_MATCH("DEATH-MATCH"),
    REGICIDE("REGICIDE"),
    //Starting Age
    DARK_AGE_START("DARK-AGE-START"),
    FEUDAL_AGE_START("FEUDAL-AGE-START"),
    CASTLE_AGE_START("CASTLE-AGE-START"),
    IMPERIAL_AGE_START("IMPERIAL-AGE-START"),
    POST_IMPERIAL_AGE_START("POST-IMPERIAL-AGE-START"),
    //Starting Resources
    LOW_RESOURCES_START("LOW-RESOURCES-START"),
    MEDIUM_RESOURCES_START("MEDIUM-RESOURCES-START"),
    HIGH_RESOURCES_START("HIGH-RESOURCES-START"),
    //Map Size 
    TINY_MAP("TINY-MAP"),
    SMALL_MAP("SMALL-MAP"),
    MEDIUM_MAP("MEDIUM-MAP"),
    NORMAL_MAP("NORMAL-MAP"),
    LARGE_MAP("LARGE-MAP"),
    GIANT_MAP("GIANT-MAP"),
    //Map Type
    ARABIA_MAP("ARABIA-MAP"),
    ARCHIPELAGO_MAP("ARCHIPELAGO-MAP"),
    BALTIC_MAP("BALTIC-MAP"),
    BLACK_FOREST_MAP("BLACK-FOREST-MAP"),
    COASTAL_MAP("COASTAL-MAP"),
    CONTINENTAL_MAP("CONTINENTAL-MAP"),
    CRATER_LAKE_MAP("CRATER-LAKE-MAP"),
    FORTRESS_MAP("FORTRESS-MAP"),
    GOLD_RUSH_MAP("GOLD-RUSH-MAP"),
    HIGHLAND_MAP("HIGHLAND-MAP"),
    ISLANDS_MAP("ISLANDS-MAP"),
    MEDITERRANEAN_MAP("MEDITERRANEAN-MAP"),
    MIGRATION_MAP("MIGRATION-MAP"),
    RIVERS_MAP("RIVERS-MAP"),
    TEAM_ISLANDS_MAP("TEAM-ISLANDS-MAP"),
    SCENARIO_MAP("SCENARIO-MAP"),
    //Victory Type
    VICTORY_STANDARD("VICTORY-STANDARD"),
    VICTORY_CONQUEST("VICTORY-CONQUEST"),
    VICTORY_TIME_LIMIT("VICTORY-TIME-LIMIT"),
    VICTORY_SCORE("VICTORY-SCORE"),
    VICTORY_CUSTOM("VICTORY-CUSTOM"),
    //Difficulty
    DIFFICULTY_EASIEST("DIFFICULTY-EASIEST"),
    DIFFICULTY_EASY("DIFFICULTY-EASY"),
    DIFFICULTY_MODERATE("DIFFICULTY-MODERATE"),
    DIFFICULTY_HARD("DIFFICULTY-HARD"),
    DIFFICULTY_HARDEST("DIFFICULTY-HARDEST"),
    //Population Cap
    POPULATION_CAP_25("POPULATION-CAP-25"),
    POPULATION_CAP_50("POPULATION-CAP-50"),
    POPULATION_CAP_75("POPULATION-CAP-75"),
    POPULATION_CAP_100("POPULATION-CAP-100"),
    POPULATION_CAP_125("POPULATION-CAP-125"),
    POPULATION_CAP_150("POPULATION-CAP-150"),
    POPULATION_CAP_175("POPULATION-CAP-175"),
    POPULATION_CAP_200("POPULATION-CAP-200"),
    //Game Speed Lock
    GAME_SPEED_LOCKED("GAME-SPEED-LOCKED"),
    //Team Lock
    TEAMS_LOCKED("TEAMS-LOCKED"),
    //Player's Civ
    GAIA("GAIA"),
    BRITON_CIV("BRITON-CIV"),
    BYZANTINE_CIV("BYZANTINE-CIV"),
    CELTIC_CIV("CELTIC-CIV"),
    CHINESE_CIV("CHINESE-CIV"),
    FRANKISH_CIV("FRANKISH-CIV"),
    GOTHIC_CIV("GOTHIC-CIV"),
    JAPANESE_CIV("JAPANESE-CIV"),
    MONGOL_CIV("MONGOL-CIV"),
    PERSIAN_CIV("PERSIAN-CIV"),
    SARACEN_CIV("SARACEN-CIV"),
    TEUTONIC_CIV("TEUTONIC-CIV"),
    TURKISH_CIV("TURKISH-CIV"),
    VIKING_CIV("VIKING-CIV");

    private final String value;

    private SystemSymbols(String value) {
        this.value = value;
    }

    @Override
    public String value() {
        return value;
    }

}
