package com.etherblood.aoe2.ai.core.variables.parameters.researches;

/**
 *
 * @author Philipp
 */
public enum Researches implements Research {
    MY_UNIQUE_UNIT_UPGRADE("my-unique-unit-upgrade"),
    //TC
    FEUDAL_AGE("feudal-age"),
    CASTLE_AGE("castle-age"),
    IMPERIAL_AGE("imperial-age"),
    LOOM("ri-loom"),
    WHEEL_BARROW("ri-wheel-barrow"),
    HAND_CART("ri-hand-cart"),
    TOWN_WATCH("ri-town-watch"),
    TOWN_PATROL("ri-town-patrol"),
    //MILL
    HORSE_COLLAR("ri-horse-collar"),
    HEAVY_PLOW("ri-heavy-plow"),
    CROP_ROTATION("ri-crop-rotation"),
    //LUMBER-CAMP
    DOUBLE_BIT_AXE("ri-double-bit-axe"),
    BOW_SAW("ri-bow-saw"),
    TWO_MAN_SAW("ri-two-man-saw"),
    //MINING-CAMP
    GOLD_MINING("ri-gold-mining"),
    STONE_MINING("ri-stone-mining"),
    GOLD_SHAFT_MINING("ri-gold-shaft-mining"),
    STONE_SHAFT_MINING("ri-stone-shaft-mining"),
    //MARKET
    CARTOGRAPHY("ri-cartography"),
    COINAGE("ri-coinage"),
    CARAVAN("ri-caravan"),
    BANKING("ri-banking"),
    GUILDS("ri-guilds"),
    //BLACKSMITH
    PADDED_ARCHER_ARMOR("ri-padded-archer-armor"),
    LEATHER_ARCHER_ARMOR("ri-leather-archer-armor"),
    RING_ARCHER_ARMOR("ri-ring-archer-armor"),
    FLETCHING("ri-fletching"),
    BODKIN_ARROW("ri-bodkin-arrow"),
    BRACER("ri-bracer"),
    FORGING("ri-forging"),
    IRON_CASTING("ri-iron-casting"),
    BLAST_FURNANCE("ri-blast-furnace"),
    SCALE_BARDING("ri-scale-barding"),
    CHAIN_BARDING("ri-chain-barding"),
    PLATE_BARDING("ri-plate-barding"),
    SCALE_MAIL("ri-scale-mail"),
    CHAIN_MAIL("ri-chain-mail"),
    PLATE_MAIL("ri-plate-mail"),
    //UNIVERSITY
    MASONRY("ri-masonry"),
    FORTIFIED_WALL("ri-fortified-wall"),
    BALLISTICS("ri-ballistics"),
    HEATED_SHOT("ri-heated-shot"),
    MURDER_HOLES("ri-murder-holes"),
    STONECUTTING("ri-stonecutting"),
    ARCHITECTURE("ri-architecture"),
    CHEMISTRY("ri-chemistry"),
    SIEGE_ENGINEERS("ri-siege-engineers"),
    GUARD_TOWER("ri-guard-tower"),
    KEEP("ri-keep"),
    BOMBARD_TOWER("ri-bombard-tower"),
    //BARRACKS
    MAN_AT_ARMS("ri-man-at-arms"),
    LONG_SWORDSMAN("ri-long-swordsman"),
    TWO_HANDED_SWORDSMAN("ri-two-handed-swordsman"),
    CHAMPION("ri-champion"),
    PIKEMAN("ri-pikeman"),
    HALBERDIER("ri-halberdier"),
    ELITE_EAGLE_WARRIOR("ri-elite-eagle-warrior"),
    TRACKING("ri-tracking"),
    SQUIRES("ri-squires"),
    //ARCHERY RANGE
    CROSSBOW("ri-crossbow"),
    ARBALEST("ri-arbalest"),
    ELITE_SKIRMISHER("ri-elite-skirmisher"),
    HEAVY_CAVALRY_ARCHER("ri-heavy-cavalry-archer"),
    THUMB_RING("ri-thumb-ring"),
    PARTHIAN_TACTICS("ri-parthian-tactics"),
    HAND_CANNON("ri-hand-cannon"),
    //STABLE
    LIGHT_CAVALRY("ri-light-cavalry"),
    HUSSAR("ri-hussar"),
    CAVALIER("ri-cavalier"),
    PALADIN("ri-paladin"),
    HEAVY_CAMEL("ri-heavy-camel"),
    BLOODLINES("ri-bloodlines"),
    HUSBANDRY("ri-husbandry"),
    //SIEGE WORKSHOP
    ONAGER("ri-onager"),
    SIEGE_ONAGER("ri-siege-onager"),
    CAPPED_RAM("ri-capped-ram"),
    SIEGE_RAM("ri-siege-ram"),
    HEAVY_SCORPION("ri-heavy-scorpion"),
    //Monastery
    REDEMPTION("ri-redemption"),
    FERVOR("ri-fervor"),
    SANCTITY("ri-sanctity"),
    ATONEMENT("ri-atonement"),
    HERBAL_MEDICINE("441"),
    HERESY("ri-heresy"),
    BLOCK_PRINTING("ri-block-printing"),
    ILLUMINATION("ri-illumination"),
    FAITH("ri-faith"),
    THEOCRACY("ri-theocracy"),
    //Dock
    WAR_GALLEY("ri-war-galley"),
    GALLEON("ri-galleon"),
    FAST_FIRE_SHIP("ri-fast-fire-ship"),
    HEAVY_DEMOLITION_SHIP("ri-heavy-demolition-ship"),
    CANNON_GALLEON("ri-cannon-galleon"),
    DECK_GUNS("ri-deck-guns"),
    SHIPWRIGHT("ri-shipwright"),
    CAREENING("ri-careening"),
    DRY_DOCK("ri-dry-dock"),
    //Castle
    HOARDINGS("ri-hoardings"),
    SAPPERS("ri-sappers"),
    CONSCRIPTION("ri-conscription"),
    SPIES("408"),
    //Aztecs
    ELITE_JAGUAR_MAN("ri-elite-jaguar-man"),
    GARLAND_WARS("24"),
    //Byzantines
    ELITE_CATAPHRACT("ri-elite-cataphract"),
    LOGISTICA("61"),
    //Celts
    ELITE_WOAD_RAIDER("ri-elite-woad-raider"),
    FUROR_CELTICA("5"),
    //Chinese
    ELITE_CHU_KO_NU("ri-elite-chu-ko-nu"),
    ROCKETRY("52"),
    //English
    ELITE_LONGBOWMAN("ri-elite-longbowman"),
    YEOMEN("3"),
    //Franks
    ELITE_THROWING_AXEMAN("ri-elite-throwing-axeman"),
    BEARDED_AXE("83"),
    //Goths
    ELITE_HUSKARL("ri-elite-huskarl"),
    ANARCHY("16"),
    PERFUSION("457"),
    //Huns
    ELITE_TARKAN("ri-elite-tarkan"),
    ATHEISM("21"),
    //Japanese
    ELITE_SAMURAI("ri-elite-samurai"),
    KATAPARUTO("59"),
    //Koreans
    ELITE_WAR_WAGON("ri-elite-war-wagon"),
    ELITE_TURTLE_SHIP("ri-elite-turtle-ship"),
    SHINKICHON("445"),
    //Mayans
    ELITE_PLUMED_ARCHER("ri-elite-plumed-archer"),
    EL_DORADO("4"),
    //Mongols
    ELITE_MANGUDAI("ri-elite-mangudai"),
    DRILL("6"),
    //Persians
    ELITE_WAR_ELEPHANT("ri-elite-war-elephant"),
    MAHOUTS("7"),
    //Sarcens
    ELITE_MAMELUKE("ri-elite-mameluke"),
    ZEALOTRY("9"),
    //Spanish
    ELITE_CONQUISTADOR("ri-elite-conquistador"),
    SUPREMACY("440"),
    //Teutons
    ELITE_TEUTONIC_KNIGHT("ri-elite-teutonic-knight"),
    CRENELLATIONS("11"),
    //Turks
    ELITE_JANISSARY("ri-elite-janissary"),
    ARTILLERY("10"),
    //Vikings
    ELITE_BERSERKER("398"),
    ELITE_LONGBOAT("ri-elite-longboat"),
    BERSERKERGANG("49");

    private final String value;

    private Researches(String value) {
        this.value = value;
    }

    @Override
    public String value() {
        return value;
    }
}
